### ISSUE TITLE
Can't load files on easyfmridata@sourceforge

### ISSUE THREAD

**Issue by vitruvi** [easyfmri/easyfmri#2]
Matlab files on easyfmridata@sourceforge give following error for hyperalignment GPUHA: 
tuple index out of range
Cannot load data file!

For hyperalignment, the file frmFAHAGPU.py expects "train_data" attribute but hosted files do not have this attribute.

How can I use preprocessed files on easyfmridata@sourceforge for hyperalignment with your code? Am I skipping a step before hyperalignment?

**Comment by myousefnezhad** [comment]
Well, the (unsupervised) Matlab files shared with the Sourceforge do not have any cross-validation. You must first cross-validate it using:

Feature Analysis -> Feature Design -> Cross Validation -> Cross Validation

--- perhaps in Subject-Level. easy fMRI will generate a single file per fold for you, including train_data and test_data rather than data.
